import { ai, db, error, json, requireAuth, storage } from '@appdeploy/sdk';
import { createUserTask } from './workflows';

type DataMap = Record<string, unknown>;
type ReferenceImage = { data: string; mimeType: string };
const imageModes=['HEADSHOT','PORTFOLIO_BEAUTIFY','MARKETING','PRESENTATION','MENU_PRODUCT'] as const;
const now=()=>new Date().toISOString();

function imagePrompt(mode:string,userPrompt:string) {
  const base='Premium culinary marketplace visual. No logos, badges, certification seals or text rendered inside the image. Never imply licensing, verification, ratings or legal compliance.';
  if(mode==='HEADSHOT') return `${base} Create a polished professional culinary headshot using the supplied reference image. Preserve the subject identity, age, skin tone and facial structure. Do not reshape the body or face, do not sexualize the subject, and use fully clothed age-appropriate chef or business attire. Improve only lighting, crop, color balance, background and professional presentation. Clean navy, cream and subtle gold editorial environment. ${userPrompt}`;
  if(mode==='PORTFOLIO_BEAUTIFY') return `${base} Beautify the supplied culinary portfolio image by improving lighting, color balance, background cleanliness, framing and premium presentation while preserving the actual dish or culinary work. Do not fabricate ingredients, awards, certifications or customer claims. ${userPrompt}`;
  if(mode==='MARKETING') return `${base} Create a sophisticated advertising image for a culinary professional marketplace. Editorial food-service photography, premium navy/cream/gold atmosphere, clean negative space for later headline overlays, modern local-service campaign aesthetic. ${userPrompt}`;
  if(mode==='PRESENTATION') return `${base} Create elegant presentation-slide decor and a premium culinary business backdrop with refined negative space, subtle tableware/culinary motifs, navy/cream/gold executive styling, uncluttered composition. ${userPrompt}`;
  return `${base} Create premium menu or culinary product photography suitable for a professional service card or product offer. Clean commercial lighting, accurate realistic food presentation, upscale editorial styling and negative space. ${userPrompt}`;
}
function safeExt(mime:string){return mime==='image/jpeg'?'jpg':mime==='image/webp'?'webp':'png';}
function creativeSystem(){return 'You are the CulinaLink premium content studio. Produce polished culinary-marketplace copy. Never invent credentials, licenses, permits, verification, ratings, customer counts, availability, health claims, guaranteed outcomes, legal compliance or prices the user did not supply. Avoid exploitative or sexualized presentation. Keep claims factual and clearly distinguish proposed marketing language from verified platform facts.';}

export const creativeRoutes={
  'GET /api/creative/presets':[async()=>json({imageModes:[{id:'HEADSHOT',label:'Professional headshot',requiresReference:true},{id:'PORTFOLIO_BEAUTIFY',label:'Portfolio beautification',requiresReference:true},{id:'MARKETING',label:'Marketing image',requiresReference:false},{id:'PRESENTATION',label:'Presentation decor',requiresReference:false},{id:'MENU_PRODUCT',label:'Menu / product image',requiresReference:false}],copyTypes:['PROFILE_BIO','SOCIAL_CAMPAIGN','SERVICE_LISTING','EVENT_PROMOTION','PRESENTATION_COPY','SEO_LANDING_PAGE'],productTypes:['PRIVATE_CHEF_PACKAGE','MEAL_PREP_PACKAGE','EVENT_PACKAGE','CULINARY_STAFFING_PACKAGE','CORPORATE_SERVICE_PACKAGE']})],
  'POST /api/creative/image':[requireAuth(),async ctx=>{const userId=ctx.user!.userId,b=(ctx.body||{}) as DataMap,mode=String(b.mode||'MARKETING'); if(!imageModes.includes(mode as typeof imageModes[number])) return error('invalid_image_mode',400); const ref=(b.reference||null) as ReferenceImage|null; if((mode==='HEADSHOT'||mode==='PORTFOLIO_BEAUTIFY')&&!ref) return error('reference_image_required',400); if(ref&&b.rightsConfirmed!==true) return error('reference_image_rights_confirmation_required',400); if(ref&&(!String(ref.mimeType||'').startsWith('image/')||!String(ref.data||''))) return error('invalid_reference_image',400); try{const result=await ai.imageGen({prompt:imagePrompt(mode,String(b.prompt||'')),images:ref?[{data:ref.data,mimeType:ref.mimeType}]:undefined,maxOutputBytes:900000}); const ext=safeExt(result.image.mimeType),path=`creative/${userId}/${Date.now()}-${mode.toLowerCase()}.${ext}`; const [ok]=await storage.write([{path,content:result.image.data,contentType:result.image.mimeType}]); if(!ok) return error('generated_asset_write_failed',500); const [{url}]=await storage.url([path]); const [id]=await db.add(`creative_assets:${userId}`,[{mode,path,mimeType:result.image.mimeType,label:'AI_ASSISTED',rightsConfirmed:b.rightsConfirmed===true,prompt:String(b.prompt||''),createdAt:now()}]); await createUserTask(userId,`CREATIVE_REVIEW_${id||Date.now()}`,'Review the AI-assisted creative asset before publishing','CREATIVE','NORMAL','AI_IMAGE_GENERATED'); return json({assetId:id,url,mode,label:'AI_ASSISTED',message:'Creative asset generated. Review it before publication; it is not evidence of credentials or real-world service outcomes.'});}catch(err){const rpc=err as {statusCode?:number,responseText?:string}; if(rpc.statusCode===429) return error('creative_rate_limited_try_again_later',429); console.error('creative image generation failed',rpc.responseText||err); return error('creative_generation_failed',500);}}],
  'GET /api/creative/assets':[requireAuth(),async ctx=>{const items=(await db.list<{path:string;mode:string;label:string;createdAt:string}>(`creative_assets:${ctx.user!.userId}`,{limit:30})).items; if(!items.length) return json({assets:[]}); const urls=await storage.url(items.map(x=>x.path)); const byPath=new Map(urls.map(x=>[x.path,x.url])); return json({assets:items.map(x=>({...x,url:byPath.get(x.path)||null}))});}],
  'POST /api/creative/copy':[requireAuth(),async ctx=>{const userId=ctx.user!.userId,b=(ctx.body||{}) as DataMap; if(!String(b.subject||'').trim()) return error('subject_required',400); try{const result=await ai.generate({system:creativeSystem(),prompt:`Create premium ${String(b.type||'CULINARY_MARKETING')} content for: ${String(b.subject)}. Audience: ${String(b.audience||'local customers and businesses')}. Offer or service: ${String(b.offer||'culinary services')}. Tone: ${String(b.tone||'premium, professional, local and confident')}. Call to action: ${String(b.cta||'Book or request a quote')}. Return a strong headline, short value proposition, 3 benefit bullets, CTA, social caption, SEO title and meta description.`,thinkingMode:'FAST',temperature:.7,maxTokens:1400}); const [id]=await db.add(`creative_copy:${userId}`,[{type:String(b.type||'CULINARY_MARKETING'),subject:String(b.subject),text:result.text,label:'AI_ASSISTED_DRAFT',createdAt:now()}]); await createUserTask(userId,`COPY_REVIEW_${id||Date.now()}`,'Review generated marketing copy for factual accuracy before publishing','CREATIVE','NORMAL','AI_COPY_GENERATED'); return json({copyId:id,text:result.text,label:'AI_ASSISTED_DRAFT'});}catch(err){const rpc=err as {statusCode?:number}; if(rpc.statusCode===429) return error('creative_rate_limited_try_again_later',429); console.error('creative copy generation failed',err); return error('copy_generation_failed',500);}}],
  'POST /api/creative/product':[requireAuth(),async ctx=>{const userId=ctx.user!.userId,b=(ctx.body||{}) as DataMap; if(!String(b.service||'').trim()) return error('service_required',400); try{const result=await ai.generate({system:creativeSystem(),prompt:`Develop a premium culinary service product offer. Product type: ${String(b.productType||'CULINARY_SERVICE_PACKAGE')}. Core service: ${String(b.service)}. Target customer: ${String(b.customer||'local households and businesses')}. Market: ${String(b.market||'Central Texas')}. User-supplied target price or pricing concept: ${String(b.price||'not supplied')}. Build: offer name, positioning statement, ideal customer, scope/deliverables, exclusions, pricing model recommendation without inventing an exact price when none is supplied, booking requirements, upsells, differentiation, launch checklist, landing-page hero copy, three campaign angles, SEO title/meta description and a concise presentation-deck outline. Never claim regulatory approval or verification.`,thinkingMode:'DEEP',temperature:.6,maxTokens:2200}); const [id]=await db.add(`product_projects:${userId}`,[{productType:String(b.productType||'CULINARY_SERVICE_PACKAGE'),service:String(b.service),plan:result.text,label:'AI_ASSISTED_PRODUCT_DRAFT',createdAt:now()}]); await createUserTask(userId,`PRODUCT_REVIEW_${id||Date.now()}`,'Review and operationalize the product offer before launch','PRODUCT_DEVELOPMENT','HIGH','AI_PRODUCT_PLAN_GENERATED'); return json({productId:id,plan:result.text,label:'AI_ASSISTED_PRODUCT_DRAFT'});}catch(err){const rpc=err as {statusCode?:number}; if(rpc.statusCode===429) return error('creative_rate_limited_try_again_later',429); console.error('product generation failed',err); return error('product_generation_failed',500);}}],
  'POST /api/creative/project':[requireAuth(),async ctx=>{const userId=ctx.user!.userId,b=(ctx.body||{}) as DataMap; const [id]=await db.add(`creative_projects:${userId}`,[{name:String(b.name||'Untitled campaign'),headline:String(b.headline||''),subheadline:String(b.subheadline||''),cta:String(b.cta||''),format:String(b.format||'SQUARE'),assetUrl:String(b.assetUrl||''),status:'DRAFT',createdAt:now()}]); if(!id) return error('project_save_failed',500); await createUserTask(userId,`CAMPAIGN_${id}_REVIEW`,'Review campaign canvas and final claims before publishing','CREATIVE','NORMAL','CAMPAIGN_PROJECT_SAVED'); return json({projectId:id,status:'DRAFT'});}]
};
