-- CulinaLink Texas rapid! contractor-disbursement reference schema
CREATE TABLE IF NOT EXISTS rapid_pay_enrollments (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID NOT NULL,provider VARCHAR(64) NOT NULL DEFAULT 'rapid! Disbursements',product_preference VARCHAR(64) NOT NULL,status VARCHAR(64) NOT NULL,kyc_status VARCHAR(64) NOT NULL DEFAULT 'PROVIDER_REQUIRED',card_status VARCHAR(64) NOT NULL DEFAULT 'NOT_ISSUED',provider_reference VARCHAR(128),voluntary_choice BOOLEAN NOT NULL DEFAULT FALSE,disclosures_accepted BOOLEAN NOT NULL DEFAULT FALSE,identity_verification_consent BOOLEAN NOT NULL DEFAULT FALSE,electronic_delivery_consent BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS rapid_pay_cards (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),enrollment_id UUID NOT NULL REFERENCES rapid_pay_enrollments(id),provider_card_token VARCHAR(160),last4 CHAR(4),network VARCHAR(32),form_factor VARCHAR(32),status VARCHAR(64) NOT NULL DEFAULT 'NOT_ISSUED',issued_at TIMESTAMPTZ,activated_at TIMESTAMPTZ,closed_at TIMESTAMPTZ,CHECK (provider_card_token IS NULL OR length(provider_card_token)>0));
CREATE TABLE IF NOT EXISTS rapid_pay_payout_preferences (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID NOT NULL,method VARCHAR(64) NOT NULL,status VARCHAR(64) NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS rapid_pay_disclosures (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),enrollment_id UUID NOT NULL REFERENCES rapid_pay_enrollments(id),document_type VARCHAR(64) NOT NULL,provider_version VARCHAR(64),accepted_at TIMESTAMPTZ,evidence JSONB NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS rapid_pay_card_actions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),enrollment_id UUID NOT NULL REFERENCES rapid_pay_enrollments(id),action VARCHAR(64) NOT NULL,status VARCHAR(64) NOT NULL DEFAULT 'PENDING_PROVIDER',provider_reference VARCHAR(128),reason TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),resolved_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS rapid_pay_payout_orders (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),contractor_id UUID NOT NULL,compensation_payment_id UUID,amount NUMERIC(14,2) NOT NULL CHECK(amount>=0),status VARCHAR(64) NOT NULL DEFAULT 'DRAFT',provider_reference VARCHAR(128),settlement_reference VARCHAR(128),created_at TIMESTAMPTZ NOT NULL DEFAULT now(),settled_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS rapid_pay_events (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),enrollment_id UUID,provider_event_id VARCHAR(160),event_type VARCHAR(96) NOT NULL,event_status VARCHAR(64) NOT NULL,payload_digest VARCHAR(128),created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_rapid_pay_enrollments_user_status ON rapid_pay_enrollments(user_id,status);
CREATE INDEX IF NOT EXISTS idx_rapid_pay_cards_enrollment_status ON rapid_pay_cards(enrollment_id,status);
CREATE INDEX IF NOT EXISTS idx_rapid_pay_payout_orders_contractor_status ON rapid_pay_payout_orders(contractor_id,status);
-- Security mandate: never persist PAN, CVV, PIN, full SSN, or full bank-account credentials in these tables.