import Head from 'next/head';
import SiteHeader from '../components/SiteHeader';

export default function Legal() {
    return <><Head><title>Terms, Privacy & Disclosures | CulinaLinkTX</title></Head><SiteHeader/><main className='page legal-copy'>
        <section id='terms'><div className='eyebrow'>Marketplace terms</div><h1>Terms of use</h1><p>CulinaLinkTX operates a culinary-services marketplace. Providers remain responsible for their services and for satisfying applicable requirements for the work, location, facility and jurisdiction. A profile, uploaded document or preliminary compliance result is not a government license, endorsement or guarantee.</p><p>Bookings, payments, payouts and deliveries use explicit lifecycle states. Requested, queued, submitted and processing states are not represented as completed until the applicable system of record or external provider confirms completion.</p></section>
        <section id='privacy'><div className='eyebrow'>Privacy</div><h2>Privacy and data protection</h2><p>CulinaLinkTX minimizes sensitive data, scopes private records to authorized users and separates operational records from external processors. Private provider residential addresses are not made public unless intentionally designated as public pickup locations.</p><p>Users may request access, correction, deletion review, portability, opt-out review or appeal through the Privacy & Data Protection Center. Retention may continue where required for financial, tax, fraud-prevention, dispute, security or audit obligations.</p><a className='btn btn-primary' href='../privacy-center/'>Open Privacy & Data Protection Center</a></section>
        <section id='ai'><div className='eyebrow'>AI notice</div><h2>Andreaa and AI-assisted content</h2><p>Andreaa provides navigation, status interpretation and bounded operational guidance. AI-generated advertising, copy and images are drafts requiring human review. AI output cannot approve credentials, authorize payment, dispatch delivery, grant government permission or create a verified status.</p></section>
        <section id='fulfillment'><div className='eyebrow'>Fulfillment</div><h2>Third-party integrations</h2><p>Delivery, payout, payment, maps, communications and identity services operate as adapters. Availability depends on configuration, provider approval and the relevant transaction.</p></section>
        <section id='disclaimer'><div className='eyebrow'>Important disclosure</div><h2>Legal and regulatory review</h2><p>These platform disclosures are operational policy text, not individualized legal advice. Applicable licensing, privacy, tax, employment, food-service, consumer-protection and accessibility obligations depend on facts and jurisdiction and should be reviewed with qualified counsel or the relevant authority before relying on them as a complete legal compliance determination.</p></section>
    </main></>;
}
